services:
  - type: web
    name: pes-nptel-backend
    runtime: node
    rootDir: Peer_Evaluation_V3_NPTEL/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
